#!/bin/sh

strict=false
tests=""
clang=false

for arg in "$@" ; do
    if [ "$arg" = "-strict" ] ; then
        strict=true
    elif [ "$arg" = "-clang" ] ; then
        clang=true
    elif [ -f "$arg" ] ; then
        tests="$tests $arg"
    else
        echo "Usage: $0 [-strict] [-clang]" 1>&2
        exit 1
    fi
done

if $clang ; then
    CC=clang
else
    CC=gcc
fi

if $strict ; then
    CFLAGS="-std=c99 -pedantic -Wall -Wextra -O3"
else
    CFLAGS="-std=c99 -Wno-format-extra-args"
fi
if $clang && ! $strict ; then
    CFLAGS="$CFLAGS -Wno-logical-op-parentheses"
fi

if [ ! "$tests" ] ; then
    tests=fizzbuzz??.c
fi

ok=true
failures=''
for file in $tests ; do
    echo -n .
    exe=`basename $file .c`
    out=`basename $file .c`.out
    if [ "$file" = "fizzbuzz27.c" ] ; then
        $CC $CFLAGS -pthread $file -o $exe
    else
        $CC $CFLAGS          $file -o $exe
    fi
    ./$exe >$out
    errors=`diff $out expected-output.txt | wc -l`
    if ! cmp -s $out expected-output.txt ; then
        ok=false
        failures="$failures $file"
    fi
    rm -f $exe $out
done
echo ''

if $ok ; then
    echo OK
else
    echo Failures: $failures
fi
